from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import os
import logging
from models.schemas import ChatRequest, ChatResponse, GeminiDebugResponse
from services.ai_service import AIService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Owe MVP API", description="AI-powered civic reciprocity platform")

# Initialize AI Service
ai_service = AIService()

@app.on_event("startup")
async def startup_event():
    status = ai_service.gemini_client.get_debug_status()
    if status["mode"] == "gemini":
        logger.info(f"Owe Backend starting in GEMINI mode using model {status['model']}.")
    else:
        logger.warning("Owe Backend starting in FALLBACK simulation mode.")

# Enable CORS for local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
def healthcheck():
    """Healthcheck endpoint for deployment verification."""
    return {"status": "ok"}

@app.get("/api/debug/gemini", response_model=GeminiDebugResponse)
def get_gemini_debug():
    """Runtime verification endpoint for Gemini pipeline."""
    return ai_service.gemini_client.get_debug_status()

@app.get("/api/debug/bigquery")
def get_bigquery_debug():
    """Runtime verification endpoint for BigQuery integration."""
    return ai_service.bq_service.get_debug_info()

@app.get("/api/brief")
def get_brief():
    """Returns the daily community brief synthesized by AI service."""
    try:
        return ai_service.get_daily_brief()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate brief: {str(e)}")

@app.get("/api/missions")
def get_missions():
    """Returns the list of active community missions generated by AI service."""
    try:
        return ai_service.get_missions()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch missions: {str(e)}")

@app.post("/api/chat", response_model=ChatResponse)
def chat_with_civic_ai(request: ChatRequest):
    """
    Conversational civic intelligence endpoint.
    Handles querying live datasets via prompt/Gemini structures.
    """
    try:
        response = ai_service.chat(request.message)
        return ChatResponse(
            reply=response["reply"],
            source=response.get("source"),
            engine=response.get("engine", "fallback")
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Chat error: {str(e)}")

# --- Serving Frontend (For Docker Single Container SPA setup) ---
FRONTEND_BUILD_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend", "dist")

if os.path.exists(FRONTEND_BUILD_DIR):
    # Mount specific assets directory for compiled JS/CSS
    assets_dir = os.path.join(FRONTEND_BUILD_DIR, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")

    # SPA Fallback for all other routes
    @app.get("/{fallback_path:path}")
    async def catch_all(fallback_path: str):
        if fallback_path.startswith("api"):
            raise HTTPException(status_code=404, detail="API route not found")
        
        # Check if the file is directly in the root of frontend/dist (e.g. favicon.ico, manifest.json)
        file_path = os.path.join(FRONTEND_BUILD_DIR, fallback_path)
        if os.path.exists(file_path) and os.path.isfile(file_path):
            return FileResponse(file_path)
            
        # Default fallback to React index.html
        return FileResponse(os.path.join(FRONTEND_BUILD_DIR, "index.html"))
else:
    @app.get("/{fallback_path:path}")
    def fallback(fallback_path: str):
        if fallback_path.startswith("api"):
            raise HTTPException(status_code=404, detail="API route not found")
        return {"message": "API is running. Frontend build not found. If running locally with Vite, use the Vite dev server (port 5173)."}
